version: "3.8"
services:
  valheim-server:
      image: lloesche/valheim-server:latest
      container_name: valheim
      environment:
        - SERVER_NAME=My_Server
        - WORLD_NAME=My_World
        - SERVER_PASS=password  #needs to be 5+ character.
        - UPDATE_CRON= 0****
        - UPDATE_IF_IDLE= true
        - BACKUPS_DIRECTORY=/config/backups
        - BACKUPS_MAX_AGE=3
        - BACKUPS_MAX_COUNT= 0
        - NVIDIA_VISIBLE_DEVICES=all
      ports:
        - 2456:2456/udp
        - 2457:2457/udp
      volumes:
        - /valheim-server/config:/config
        - /valheim-server/data:/opt/valheim
        - /valheim-server/worlds_local:/config/worlds_local
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
      restart: unless-stopped
